### ISSUE TITLE
token has undefined character in it

### ISSUE THREAD

**Issue by Stedfst** [coats1337/Discord-Token-Grabber#1]
� these sorta characters were in my token and I wasn't able to login with it.

**Comment by coats1337** [comment]
ever thought of removing them?

**Comment by enescaglayan** [comment]
having same issue

**Comment by enescaglayan** [comment]
i cant even get the token

**Comment by enescaglayan** [comment]
it just gives the token but it doesnt work

**Comment by enescaglayan** [comment]
and there is no characters like ���

**Comment by coats1337** [comment]
i'll figure out a fix, thanks.
